language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  include:
    - rust: stable
      os: linux
      script:
        - cargo build --release
        - cargo test --verbose
      env:
        - DEPLOY=true
    - rust: stable
      os: osx
      script:
        - cargo build --release
        - cargo test --verbose
      env:
        - DEPLOY=true
    - rust: nightly
      os: linux
      script:
        - cargo build --features clippy
#deploy:
#  - provider: releases
#  - api_key: "$GITHUB_TOKEN"
#  - file:
#      - "target/release/assembler"
#      - "target/release/disassembler"
#      - "target/release/emulator"
#  - skip_cleanup: true
#  - on:
#      - tags: true
#      - condition: "$DEPLOY = true"
